#config 2
com.instana.plugin.host:
  tags:
    - 'dev'

# Java Profiling 2
com.instana.plugin.profiling.java:
  enabled: true

# Mysql
com.instana.plugin.mysql:
  user: 'config'
  password: 'two'

# Mysql 2
com.instana.plugin.mysql:
  user: 'config'
  password: 'two'
